name: Deploy Quiz Please Scheduler with Docker

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/quiz-please-scheduler:latest .
          docker push ghcr.io/${{ github.repository }}/quiz-please-scheduler:latest
      
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Login in GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Get image
            docker pull ghcr.io/${{ github.repository }}/quiz-please-scheduler:latest
            
            # Stop and remove previous container
            docker stop quiz-please-scheduler || true
            docker rm quiz-please-scheduler || true
            
            # Run new container in background with auto-restart
            docker run -d \
              --name quiz-please-scheduler \
              --restart unless-stopped \
              -e CONFIG_PATH=/config.prod.yaml \
              -v /home/jarashow/quiz-please-scheduler/config.prod.yaml:/config.prod.yaml \
              -v /app/logs:/app/logs \
              ghcr.io/${{ github.repository }}/quiz-please-scheduler:latest
            
            # Prune old images to save disk space
            docker image prune -f